# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,-0.0062f,0f,0.9816f,0.1908f,0.825f,0f,0.1908f,-0.9816f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9994f,-0.0114f,0.033f,0f,-0.0006f,0.9511f,0.309f,1.6344f,-0.0349f,0.3088f,-0.9505f,0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.997f,-0.0771f,-0.0115f,0.275f,-0.0324f,0.5444f,-0.8382f,1.5031f,0.0709f,-0.8353f,-0.5453f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9856f,-0.1193f,-0.1202f,-0.275f,0.0514f,0.4653f,-0.8837f,1.4813f,0.1613f,-0.8771f,-0.4524f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound minecraft:item.dye.use ambient @a ~ ~ ~ 10 1 1

execute store result storage cb:infected008 minDamage int 1 run scoreboard players get minDamage infected008
execute store result storage cb:infected008 maxDamage int 1 run scoreboard players get maxDamage infected008

execute store result storage cb:infected008 minBleeding int 1 run scoreboard players get minBleeding infected008
execute store result storage cb:infected008 maxBleeding int 1 run scoreboard players get maxBleeding infected008

execute as @n[tag=infected008] at @s positioned ^ ^ ^0.5 as @a[distance=..1.35] at @s run function infected008:damage with storage cb:infected008