# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9994f,0f,0.0349f,0f,-0.0006f,0.9998f,-0.0174f,1.65f,-0.0349f,-0.0175f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=aj.infected008.root] run function animated_java:infected008/animations/attack/stop

attribute @n[tag=infected008] movement_speed modifier remove 9843-0-0-0-0