# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scp096.animation.idle_sit.playing
tag @s remove aj.scp096.animation.idle.playing
tag @s remove aj.scp096.animation.rage_in.playing
tag @s remove aj.scp096.animation.attack_basic.playing
tag @s remove aj.scp096.animation.run.playing