# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.scp096.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'scp096', 'function_path': 'animated_java:scp096/animations/pause_all'}
tag @s remove aj.scp096.animation.idle_sit.playing
tag @s remove aj.scp096.animation.idle.playing
tag @s remove aj.scp096.animation.rage_in.playing
tag @s remove aj.scp096.animation.attack_basic.playing
tag @s remove aj.scp096.animation.run.playing
tag @s remove aj.scp096.animation.run_.playing
tag @s remove aj.scp096.animation.idle_sit_.playing
tag @s remove aj.scp096.animation.idle_.playing
tag @s remove aj.scp096.animation.rage_in_.playing
tag @s remove aj.scp096.animation.attack_basic_.playing