# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp049_2d.root] run return 0
execute on passengers if entity @s[tag=aj.scp049_2d.data] unless data entity @s {data:{rigHash: 'de602f9ffad3d95217d15b4b3e41ffa2d9e5a5f9e51feff839cef6baf32cb474'}} on vehicle run function animated_java:scp049_2d/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1