# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,1.1694f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-1.1694f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute if entity @n[tag=elevator, tag=049, tag=1, distance=..5] if score .state chamber049.event matches 0 run function events:049/1