# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,1.4658f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-1.4658f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound cb:elev.close ambient @a[distance=..24] ~ ~1 ~ 1 1 1