# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.7994f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.7994f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

# execute if entity @s[y_rotation=0] run fill ^ ^ ^ ^-1 ^1 ^ lightning_rod[facing=west]
# execute if entity @s[y_rotation=180] run fill ^ ^ ^ ^-1 ^1 ^ lightning_rod[facing=west]

# execute if entity @s[y_rotation=90] run fill ^ ^ ^ ^-1 ^1 ^ lightning_rod[facing=north]
# execute if entity @s[y_rotation=270] run fill ^ ^ ^ ^-1 ^1 ^ lightning_rod[facing=north]

execute as @n[tag=elevatorDoors] if entity @s[tag=r0] run fill ~ ~ ~ ~ ~1 ~-1 lightning_rod[facing=north]
execute as @n[tag=elevatorDoors] if entity @s[tag=r1] run fill ~ ~ ~ ~-1 ~1 ~ lightning_rod[facing=west]

tag @n[tag=elevatorDoors] add closed
tag @n[tag=elevatorDoors] remove opened