# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.5474f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.5474f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

# basic ambient stopsound goes here
playsound cb:scp049.chamber0 ambient @a[tag=location.049chamber, tag=insideElevator] ~ ~ ~ 0.6 1 1