# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.5474f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.5474f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

# basic ambient stopsound goes here
stopsound @a[tag=location.939storage, tag=insideElevator] * cb:zone1.mainambient
scoreboard players set @a[tag=location.939storage, tag=insideElevator] zoneambientlcz -1


stopsound @a[tag=location.049chamber, tag=insideElevator] * cb:zone2.mainambient
scoreboard players set @a[tag=location.939chamber, tag=insideElevator] zoneambienthcz -1

#g surface init
stopsound @a[tag=location.surface, tag=insideElevator] * cb:zone3.mainambient
scoreboard players set @a[tag=location.surface, tag=insideElevator] zoneambientez -1

#g ending init
execute if entity @p[tag=location.surfaceA] run scoreboard players set .gateSelected e 1
execute if entity @p[tag=location.surfaceB] run scoreboard players set .gateSelected e 2

execute if entity @p[tag=location.surface] unless score .selected e matches 0 unless score .selected e matches 1 unless score .selected e matches 2 unless score .selected e matches 3 run function endings:define

#g
execute as @a[tag=location.surface] at @s run function save_progress:save {"sound":"none"}
tag @a[tag=location.surface] remove ez
execute as @a[tag=location.surface] at @s run function shader_control:effects/blue/set {"value":"0.0"}
execute as @a[tag=location.surface] at @s run scoreboard players set @s shader.brightness 60
execute as @a[tag=location.surface] at @s run scoreboard players set @s shader.saturation 5

scoreboard players operation @a[tag=location.049chamber, tag=insideElevator] chamber049.ambientTimer = .max chamber049.ambientTimer
scoreboard players operation @a[tag=location.939storage, tag=insideElevator] 939.ambient = .loop 939.ambient


effect give @a[tag=!location.106chamber, tag=insideElevator] darkness infinite 1 true
effect give @a[tag=!location.049chamber, tag=insideElevator] darkness infinite 1 true
effect give @a[tag=!location.surfaceA, tag=insideElevator] darkness infinite 1 true
effect give @a[tag=!location.surfaceB, tag=insideElevator] darkness infinite 1 true
effect give @a[tag=!location.nuke, tag=insideElevator] darkness infinite 1 true

effect clear @a[tag=location.nuke] darkness
effect clear @a[tag=location.106chamber] darkness
effect clear @a[tag=location.049chamber] darkness
effect clear @a[tag=location.surfaceA] darkness
effect clear @a[tag=location.surfaceB] darkness