# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.685f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.685f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

scoreboard players set @a[tag=!location.049chamber, tag=insideElevator] chamber049.ambientTimer -1
stopsound @a[tag=!location.049chamber, tag=insideElevator] ambient cb:scp049.chamber0

scoreboard players set @a[tag=!location.939storage, tag=insideElevator] 939.ambient -1
stopsound @a[tag=!location.939storage, tag=insideElevator] ambient cb:scp939.ambient