# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.914_start.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': '914_start', 'function_path': 'animated_java:914_start/remove/this'}
execute on passengers run kill @s
kill @s