# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.914_start.root] run return 0
execute on passengers if entity @s[tag=aj.914_start.data] unless data entity @s {data:{rigHash: '0581e90c083d728b9692f7dcd4988fb2ab1c5eaa5ee78c481ba644ddcb3a788c'}} on vehicle run function animated_java:914_start/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1