# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.914_start.root] run return 0
execute if entity @s[tag=aj.914_start.animation.start.playing] run function animated_java:914_start/animations/start/zzz/on_tick
execute on passengers run rotate @s ~ ~