# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scp939.animation.idle.playing
tag @s remove aj.scp939.animation.attack.playing
tag @s remove aj.scp939.animation.walk.playing
tag @s remove aj.scp939.animation.run.playing