# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.attack_basic.frame matches 47.. run scoreboard players set @s aj.attack_basic.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.attack_basic.frame
execute at @s run function animated_java:scp096/animations/attack_basic/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.attack_basic.frame 1