# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp008 rig_hash set value 'f1e23f427d8bfae3bb3d4768710e30f7fa4a2b067a00ebf91d10af964e991dd7'
scoreboard objectives add aj.close.frame dummy