# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f6b5fe284f0a08f356e165dd76e4bb6658ff3b353cff430968ea29342d7d7907'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack