# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f1e23f427d8bfae3bb3d4768710e30f7fa4a2b067a00ebf91d10af964e991dd7'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack