# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp066 rig_hash set value '700b3adfdc9dbc608285c5b431f9a02936235c5242a2579f696261dacc1c44bf'
scoreboard objectives add aj.wallow.frame dummy