# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:infected008 rig_hash set value '8eae22dd517ef1b985f193b422b61720e77a0d2a602e39af3ee44f444a90172c'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.wake.frame dummy
scoreboard objectives add aj.death.frame dummy