# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:infected008 rig_hash set value 'ec549cbbaeaa000951c81d9713eab0b923965b49c763041d0746c21dc09149f8'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.wake.frame dummy