# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:infected008 rig_hash set value 'b8575c72001ac8f864ae312b8bb3647a80ffa9860ed3616391c83eee4c2f9fae'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.wake.frame dummy