# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:elevator_doors rig_hash set value '35190fbffaf5750949837f470c71f0f3d20e3c86fc51990cb9bbf187a38c075d'
scoreboard objectives add aj.openclose.frame dummy