# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scp049_2d.animation.walk.playing
tag @s remove aj.scp049_2d.animation.idle.playing
tag @s remove aj.scp049_2d.animation.attack.playing