# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.p.node.s] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_s set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.p.node.p] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_p set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.p.node.r_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.p.node.l_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_arm set from storage aj:uuid main.out