# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door_card0.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door_card0', 'function_path': 'animated_java:door_card0/animations/openclosetoggle/play'}
tag @s add aj.door_card0.animation.openclosetoggle.playing
scoreboard players set @s aj.openclosetoggle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:door_card0/animations/openclosetoggle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only

execute as @p[scores={door_right_click=1..}] run function inventory:hotbar/set {"text":"'Keycard was inserted into the slot."}
scoreboard players set @a door_right_click 0 