# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp096/animations/run_/zzz/apply_frame {frame: 208}
scoreboard players add @s aj.run_.frame 1