# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1.3329f,-0.0233f,-0.0233f,0f,-0.0212f,1.3281f,-0.1162f,0.125f,0.0252f,-0.1158f,-1.3281f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_righthand) {transformation: [-0.7275f,-0.3655f,0.5806f,-0.5313f,-0.3208f,0.9293f,0.1831f,0.4219f,-0.6064f,-0.0531f,-0.7934f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lefthand) {transformation: [-0.8962f,0.3007f,0.3262f,0.6219f,0.2826f,0.9537f,-0.1028f,0.3438f,-0.342f,0f,-0.9397f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-0.9174f,-0.342f,-0.2034f,-0.5f,-0.3339f,0.9397f,-0.074f,0.3594f,0.2164f,0f,-0.9763f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-0.3918f,0.3746f,-0.8403f,0.5f,0.1583f,0.9272f,0.3395f,0.3594f,0.9063f,0f,-0.4226f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerjaw) {transformation: [-0.9973f,0.0523f,-0.0523f,0.0134f,0.0514f,0.9985f,0.0174f,0.4925f,0.0532f,0.0147f,-0.9985f,1.3153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9973f,0.0523f,-0.0523f,0f,0.0514f,0.9985f,0.0174f,0.6875f,0.0532f,0.0147f,-0.9985f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rhwrist) {transformation: [-0.9848f,0f,-0.1736f,-1.25f,0f,1f,0f,0.1406f,0.1736f,0f,-0.9848f,0.3437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lhwrist) {transformation: [-0.9962f,0f,0.0872f,1.2969f,0f,1f,0f,0.1406f,-0.0872f,0f,-0.9962f,1.4219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlwrist) {transformation: [-0.9962f,0f,0.0872f,-0.9687f,0f,1f,0f,0.1563f,-0.0872f,0f,-0.9962f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llwrist) {transformation: [-0.9763f,0f,-0.2164f,1.1875f,0f,1f,0f,0.1406f,0.2164f,0f,-0.9763f,-1.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute if score @n[tag=scp939] attack_cd matches 0 run playsound cb:scp939_53.attack ambient @a ~ ~ ~ 1 1 1

scoreboard players operation @n[tag=scp939] attack_cd = .max attack_cd