# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation: [-0.9988f,0.0349f,0.0352f,-0.125f,0.0355f,0.9992f,0.0162f,0.5f,-0.0346f,0.0174f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.9985f,-0.0174f,-0.0523f,0.125f,-0.0147f,0.9985f,-0.0523f,0.5f,0.0532f,-0.0514f,-0.9973f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.75f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9848f,0.1736f,0f,0.35f,0.0151f,0.0858f,-0.9962f,1.4688f,-0.173f,-0.9811f,-0.0872f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.999f,-0.0436f,0f,-0.3688f,-0.0038f,0.0871f,-0.9962f,1.4688f,0.0435f,-0.9952f,-0.0872f,0.2375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

attribute @n[tag=scp049_2] movement_speed modifier add 0492-0-0-0-3 -1.0 add_value