# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '904f39e5bd44a721252db8116f562ede9c465f2f0f3bf9c65886b026a543c17d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack