# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp1499_1 rig_hash set value 'e301077056e6ad61f98eb308fdaf42798e42aa48d3926f5a00740393887c7d46'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.point.frame dummy