# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.mtf.root] run return 0
execute on passengers if entity @s[tag=aj.mtf.data] unless data entity @s {data:{rigHash: 'afb4735239a03cdb5581b005683922825dac1d1bd8bd33894a0b945c35a4bfe6'}} on vehicle run function animated_java:mtf/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1