# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.close.frame $(frame)
execute at @s run function animated_java:scp008/animations/close/zzz/set_frame with storage animated_java:temp args