# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door1.root] run return 0
execute on passengers if entity @s[tag=aj.door1.data] unless data entity @s {data:{rigHash: '6a61022157bee3449165410d79a78bdbc01756fc2040b16d765b8d3ce96bd515'}} on vehicle run function animated_java:door1/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1