# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door1.root] run return 0
execute if entity @s[tag=aj.door1.animation.open_close_toggle.playing] run function animated_java:door1/animations/open_close_toggle/zzz/on_tick
execute on passengers run rotate @s ~ ~