# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1.25f,0f,0f,0f,0f,1.25f,0f,0f,0f,0f,-1.25f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute as @n[tag=aj.914_button.root] run function animated_java:914_button/animations/change_mode/stop