# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:airlockdoors rig_hash set value 'ff9241232fcf49a93adaada36776ba3aadb58a1d75bb2d6c9fcaad6dacc14025'
scoreboard objectives add aj.openclosetoggle.frame dummy