# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f729715992c40e51338298c359579b3e1370cbe2740820c5e6b0aa324aac2a0a'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack