# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_r_arm) {transformation: [-0.9976f,0.0667f,0.0205f,-0.275f,0.0698f,0.9537f,0.2927f,1.5156f,0f,0.2934f,-0.956f,-0.0167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.9986f,-0.0491f,0.018f,0.275f,-0.0523f,0.9377f,-0.3436f,1.4992f,0f,-0.3441f,-0.9389f,0.0052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.8125f,0f,0f,-1f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9997f,0.0173f,0.0176f,0f,0.0175f,0.9998f,0.0087f,1.6437f,-0.0174f,0.009f,-0.9998f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-0.9994f,-0.0337f,-0.0121f,0.1375f,-0.0357f,0.9176f,0.396f,0.8177f,-0.0022f,0.3961f,-0.9182f,-0.049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-0.9993f,0.0353f,0.0096f,-0.1375f,0.0326f,0.9777f,-0.2076f,0.7938f,-0.0167f,-0.2072f,-0.9782f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
playsound cb:player.step @a ambient ~ ~ ~ 1 1 1