# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_r_arm) {transformation: [-0.9968f,0.0781f,0.0155f,-0.275f,0.0679f,0.9356f,-0.3466f,1.5f,-0.0415f,-0.3444f,-0.9379f,0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.9986f,-0.0498f,-0.016f,0.275f,-0.0523f,0.9511f,0.3044f,1.5169f,0f,0.3049f,-0.9524f,-0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.8125f,0f,0f,-1f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9997f,0.0173f,0.0176f,0f,0.0175f,0.9998f,0.0087f,1.6437f,-0.0174f,0.009f,-0.9998f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-0.9994f,-0.0352f,0.0063f,0.1375f,-0.0357f,0.993f,-0.113f,0.7938f,-0.0022f,-0.1131f,-0.9936f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-0.9993f,0.0352f,-0.0122f,-0.1375f,0.0276f,0.9184f,0.3947f,0.8188f,0.0251f,0.3941f,-0.9187f,-0.0553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
playsound cb:player.step @a ambient ~ ~ ~ 1 1 1