# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp1048a rig_hash set value '6753edcea28a3568e6cd70868004aa48722f62304aad8c651970ef305151dbe2'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.greet.frame dummy
scoreboard objectives add aj.shriek.frame dummy