# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3e2f9af02117a3ccb3d33f15648c8e5ae8d6c622d9e83fd75e0bb0d02c8a98e4'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack