# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp1499_1.root] run return 0
execute if entity @s[tag=aj.scp1499_1.animation.idle.playing] run function animated_java:scp1499_1/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp1499_1.animation.walk.playing] run function animated_java:scp1499_1/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.scp1499_1.animation.attack.playing] run function animated_java:scp1499_1/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.scp1499_1.animation.point.playing] run function animated_java:scp1499_1/animations/point/zzz/on_tick
execute on passengers run rotate @s ~ ~