# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.scp049.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'scp049', 'function_path': 'animated_java:scp049/animations/revive/next_frame'}
execute if score @s aj.revive.frame matches 142.. run scoreboard players set @s aj.revive.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.revive.frame
execute at @s run function animated_java:scp049/animations/revive/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.revive.frame 1