# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @n[tag=door_marker] add dr.not_rendered
function animated_java:door0/remove/this/without_on_remove_function