# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '99bafdb2771af10d41386a0936a867d9c9d8a970313dc7a0e4307ef25ef2cbf5'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack