# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.guard.animation.walk.playing
tag @s remove aj.guard.animation.idle.playing
tag @s remove aj.guard.animation.idle2.playing
tag @s remove aj.guard.animation.walk2.playing