# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.914_button.root] run return 0
execute on passengers if entity @s[tag=aj.914_button.data] unless data entity @s {data:{rigHash: '31e9b3ce775141481601afa9b6567f404fafc03c2d15ca79a01787c571f9bac2'}} on vehicle run function animated_java:914_button/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1