# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:cisolder rig_hash set value 'c2ebde81ec6301265b8d3b7d26a20b679c030a5d4af13930ac475634d62d006d'
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy