# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.airlockdoors.root] run return 0
execute if entity @s[tag=aj.airlockdoors.animation.openclosetoggle.playing] run function animated_java:airlockdoors/animations/openclosetoggle/zzz/on_tick
execute on passengers run rotate @s ~ ~