# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:class_d rig_hash set value '7981a80a01c31402e12f09f94ab2ba32e0b09df7015b8f1be9b39205283cd0eb'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.walk.frame dummy