# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:class_d rig_hash set value 'a95217320baa33077b9d709e27725c342223dced3834ad7cd818ecd5a6a9c2d0'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.walk.frame dummy