# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.m4a1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'm4a1', 'function_path': 'animated_java:m4a1/animations/reload/next_frame'}
execute if score @s aj.reload.frame matches 17.. run scoreboard players set @s aj.reload.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.reload.frame
execute at @s run function animated_java:m4a1/animations/reload/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.reload.frame 1