# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.m4a1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'm4a1', 'function_path': 'animated_java:m4a1/animations/reload/play'}
tag @s add aj.m4a1.animation.reload.playing
scoreboard players set @s aj.reload.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:m4a1/animations/reload/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only