# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp049/animations/idle_contain/zzz/apply_frame {frame: 35}
scoreboard players add @s aj.idle_contain.frame 1