# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1.3329f,-0.0233f,-0.0233f,0f,-0.0212f,1.3281f,-0.1162f,0.125f,0.0252f,-0.1158f,-1.3281f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_righthand) {transformation: [-0.9537f,-0.3007f,0f,-0.5625f,-0.3007f,0.9537f,0f,0.375f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lefthand) {transformation: [-0.9537f,0.3007f,0f,0.5625f,0.3007f,0.9537f,0f,0.375f,0f,0f,-1f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rightleg) {transformation: [-0.9397f,-0.342f,0f,-0.5f,-0.342f,0.9397f,0f,0.3594f,0f,0f,-1f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leftleg) {transformation: [-0.9272f,0.3746f,0f,0.5f,0.3746f,0.9272f,0f,0.3594f,0f,0f,-1f,-1.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lowerjaw) {transformation: [-0.9973f,0.0523f,-0.0523f,0.0134f,0.0514f,0.9985f,0.0174f,0.4925f,0.0532f,0.0147f,-0.9985f,1.3153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9973f,0.0523f,-0.0523f,0f,0.0514f,0.9985f,0.0174f,0.6875f,0.0532f,0.0147f,-0.9985f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rhwrist) {transformation: [-0.9848f,0f,-0.1736f,-1.25f,0f,1f,0f,0.1406f,0.1736f,0f,-0.9848f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_lhwrist) {transformation: [-0.9848f,0f,0.1736f,1.25f,0f,1f,0f,0.1406f,-0.1736f,0f,-0.9848f,0.8125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_rlwrist) {transformation: [-1f,0f,0f,-1.0625f,0f,1f,0f,0.1563f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_llwrist) {transformation: [-1f,0f,0f,1.0625f,0f,1f,0f,0.1406f,0f,0f,-1f,-0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
