# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp1499_1/animations/attack/zzz/apply_frame {frame: 49}
scoreboard players add @s aj.attack.frame 1