# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp106.root] run return 0
execute on passengers if entity @s[tag=aj.scp106.data] unless data entity @s {data:{rigHash: '0bfe7c5ef384b776d9342681b0ad3bc0e3fe741465747fa4c95c9cb96a2a3ecc'}} on vehicle run function animated_java:scp106/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1