# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp096.root] run return 0
execute on passengers if entity @s[tag=aj.scp096.data] unless data entity @s {data:{rigHash: '62c2b49586e09a42eff72bfa0b38539a0158d464939c1033d95e90fd6e044b4e'}} on vehicle run function animated_java:scp096/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1