# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp096.root] run return 0
execute if entity @s[tag=aj.scp096.animation.idle_sit.playing] run function animated_java:scp096/animations/idle_sit/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.idle.playing] run function animated_java:scp096/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.rage_in.playing] run function animated_java:scp096/animations/rage_in/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.attack_basic.playing] run function animated_java:scp096/animations/attack_basic/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.run.playing] run function animated_java:scp096/animations/run/zzz/on_tick
execute on passengers run rotate @s ~ ~