# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp096.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.scp096.animation.idle_sit.playing] run function animated_java:scp096/animations/idle_sit/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.idle.playing] run function animated_java:scp096/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.rage_in.playing] run function animated_java:scp096/animations/rage_in/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.attack_basic.playing] run function animated_java:scp096/animations/attack_basic/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.run.playing] run function animated_java:scp096/animations/run/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.run_.playing] run function animated_java:scp096/animations/run_/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.idle_sit_.playing] run function animated_java:scp096/animations/idle_sit_/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.idle_.playing] run function animated_java:scp096/animations/idle_/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.rage_in_.playing] run function animated_java:scp096/animations/rage_in_/zzz/on_tick
execute if entity @s[tag=aj.scp096.animation.attack_basic_.playing] run function animated_java:scp096/animations/attack_basic_/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~