# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:air
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~-1 ~ ~ minecraft:air
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~ ~1 ~ minecraft:air
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~ ~ ~ minecraft:air
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:air
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~ ~-1 minecraft:air
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~1 ~ minecraft:air
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~ ~ minecraft:air

