# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2f,0f,0f,1.6801f,0f,2f,0f,0f,0f,0f,-2f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2f,0f,0f,-1.6801f,0f,2f,0f,0f,0f,0f,-2f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

# function animated_java:door0/animations/openclosetoggle/zzz/frames/23_root_commands