# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,-0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute at @n[tag=airlockdoors] run playsound cb:door.open ambient @a[distance=..16] ~ ~1 ~ 1 1 1