# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,-1.9994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=airlock] run function animated_java:airlockdoors/animations/openclosetoggle/pause
tag @n[tag=airlock] remove proceed