# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,-1.937f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^1 ^1 lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^ ^1 lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^1 ^ lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^ ^ lightning_rod[facing=west]

execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^1 ^1 lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^ ^1 lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^1 ^ lightning_rod[facing=west]
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^ ^ lightning_rod[facing=west]

execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^5 ^1 ^1 lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^5 ^ ^1 lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^5 ^1 ^ lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^5 ^ ^ lightning_rod[facing=north]

execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^-4 ^1 ^1 lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^-4 ^ ^1 lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^-4 ^1 ^ lightning_rod[facing=north]
execute as @n[tag=airlock,y_rotation=-180] at @s run setblock ^-4 ^ ^ lightning_rod[facing=north]