# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,-0.1085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute if entity @n[tag=event3_handler173,distance=..10] run function scp173:despawn
execute at @n[tag=event3_handler173,distance=..10] run function scp173:spawn
execute if entity @n[tag=event3_handler173,distance=..10] as @n[tag=scp173] at @s run tp @s ~ ~ ~ facing entity @p
execute run kill @n[tag=event3_handler173,distance=..10]