# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,-0.0623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^1 ^1 air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^ ^1 air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^1 ^ air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^4 ^ ^ air

execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^1 ^1 air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^ ^1 air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^1 ^ air
execute as @n[tag=airlock,y_rotation=-270] at @s run setblock ^-5 ^ ^ air

execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^5 ^1 ^1 air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^5 ^ ^1 air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^5 ^1 ^ air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^5 ^ ^ air

execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^-4 ^1 ^1 air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^-4 ^ ^1 air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^-4 ^1 ^ air
execute as @n[tag=airlock,y_rotation=180] at @s run setblock ^-4 ^ ^ air