# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-6.5f,0f,0f,0f,0f,6.5f,0f,0f,0f,0f,-6.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute at @n[tag=airlockdoors] run playsound cb:event3.airlock ambient @a[distance=..32] ~ ~ ~ 1 1 1
execute as @n[tag=airlockdoors] run function animated_java:airlockdoors/animations/openclosetoggle/stop
tag @n[tag=airlock] remove proceed

execute at @n[tag=airlockdoors] run particle campfire_cosy_smoke ~ ~2 ~ 0 0.5 0 0.05 100 force
execute at @n[tag=airlockdoors] run particle campfire_cosy_smoke ~ ~2 ~ 0 0.5 0 0.05 100 force
execute at @n[tag=airlockdoors] run particle campfire_cosy_smoke ~ ~2 ~ 0 0.75 0 0.05 100 force