# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.open_close_toggle.frame matches 51.. run scoreboard players set @s aj.open_close_toggle.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.open_close_toggle.frame
execute at @s run function animated_java:door1/animations/open_close_toggle/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.open_close_toggle.frame 1