# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scientist rig_hash set value 'c8ea99859b9c49a37627ca380e504733c29543e85d485dd0d71ff6bdf9003806'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.death.frame dummy
scoreboard objectives add aj.corpse.frame dummy