# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door_card0.root] run return 0
execute on passengers if entity @s[tag=aj.door_card0.data] unless data entity @s {data:{rigHash: '8a0fe4c31c3df5993b369cd0427ada4a932c3925b788b6651ef56dfa0adad487'}} on vehicle run function animated_java:door_card0/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1