# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.door914.animation.open.playing
tag @s remove aj.door914.animation.close.playing