# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door_card0.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door_card0', 'function_path': 'animated_java:door_card0/remove/this'}
tag @n[tag=door_marker] add dr.not_rendered
execute on passengers run kill @s
kill @s