# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.l_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.r_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.l_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.r_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp049.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out