# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door0.root] run return 0
execute on passengers if entity @s[tag=aj.door0.data] unless data entity @s {data:{rigHash: '9702ced5c70dd4d24f2274d7ae20862e867b42902b14a786d1ed96f80c598a24'}} on vehicle run function animated_java:door0/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1