# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door0.root] run return 0
execute if entity @s[tag=aj.door0.animation.openclosetoggle.playing] run function animated_java:door0/animations/openclosetoggle/zzz/on_tick
execute on passengers run rotate @s ~ ~