# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.m4a1.root] run return 0
execute on passengers if entity @s[tag=aj.m4a1.data] unless data entity @s {data:{rigHash: '05d3f4bc22e7c51ba1ac53419a94aab1de0929457a4441d49fa4a2a7d1a1fd93'}} on vehicle run function animated_java:m4a1/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1