# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:celldoor rig_hash set value '865d6e23fa7590b080248d1c873a2e86f3c6e360ae70330f74780a1e15569184'
scoreboard objectives add aj.openclose.frame dummy