# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp457 rig_hash set value '3e2f9af02117a3ccb3d33f15648c8e5ae8d6c622d9e83fd75e0bb0d02c8a98e4'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy