# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.class_d.root] run return 0
execute if entity @s[tag=aj.class_d.animation.idle.playing] run function animated_java:class_d/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.class_d.animation.death.playing] run function animated_java:class_d/animations/death/zzz/on_tick
execute if entity @s[tag=aj.class_d.animation.walk.playing] run function animated_java:class_d/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~