# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '700b3adfdc9dbc608285c5b431f9a02936235c5242a2579f696261dacc1c44bf'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack