# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door_check0.root] run return 0
execute on passengers if entity @s[tag=aj.door_check0.data] unless data entity @s {data:{rigHash: '116859c064bc3ded34b018bd7a0db461c5668daaf4ef68ca750f961098c47afd'}} on vehicle run function animated_java:door_check0/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1