# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp1048a.root] run return 0
execute if entity @s[tag=aj.scp1048a.animation.walk.playing] run function animated_java:scp1048a/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.scp1048a.animation.idle.playing] run function animated_java:scp1048a/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp1048a.animation.greet.playing] run function animated_java:scp1048a/animations/greet/zzz/on_tick
execute if entity @s[tag=aj.scp1048a.animation.shriek.playing] run function animated_java:scp1048a/animations/shriek/zzz/on_tick
execute on passengers run rotate @s ~ ~