# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0047f,1.6875f,0f,-0.0047f,-1f,-0.0018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,1f,0f,0.9368f,0f,0f,-1f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,1f,-0.0091f,1.6844f,0f,-0.0091f,-1f,-0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0026f,1f,0f,-0.0026f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}