# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0095f,1.6875f,0f,-0.0095f,-1f,-0.0035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,1f,0f,0.936f,0f,0f,-1f,-0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,1f,-0.0095f,1.6843f,0f,-0.0095f,-1f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0051f,1f,0f,-0.0051f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}