# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0053f,1.6875f,0f,-0.0053f,-1f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,1f,0f,0.9368f,0f,0f,-1f,-0.0016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,1f,-0.0082f,1.6844f,0f,-0.0082f,-1f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0024f,1f,0f,-0.0024f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}