# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6753edcea28a3568e6cd70868004aa48722f62304aad8c651970ef305151dbe2'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack