# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door0.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door0', 'function_path': 'animated_java:door0/animations/openclosetoggle/next_frame'}
execute if score @s aj.openclosetoggle.frame matches 71.. run scoreboard players set @s aj.openclosetoggle.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.openclosetoggle.frame
execute at @s run function animated_java:door0/animations/openclosetoggle/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.openclosetoggle.frame 1