# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'cbed8388c5e899940af3be21f27a4a0a07957b20146d511b10fcab884bfcde46'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack