# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b2b1078dd233e0fa7e9e7656733941278d02fc6e3c35a8e54afaf6fb097fbb75'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack