# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp066.root] run return 0
execute if entity @s[tag=aj.scp066.animation.wallow.playing] run function animated_java:scp066/animations/wallow/zzz/on_tick
execute on passengers run rotate @s ~ ~