# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scientist.root] run return 0
execute if entity @s[tag=aj.scientist.animation.idle.playing] run function animated_java:scientist/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scientist.animation.death.playing] run function animated_java:scientist/animations/death/zzz/on_tick
execute if entity @s[tag=aj.scientist.animation.corpse.playing] run function animated_java:scientist/animations/corpse/zzz/on_tick
execute on passengers run rotate @s ~ ~