# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9998f,0f,0.0175f,0f,0f,1f,0f,1.65f,-0.0175f,0f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9988f,0.0343f,0.0355f,-0.275f,0.0349f,0.9993f,0.0162f,1.5125f,-0.0349f,0.0174f,-0.9992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=scp1499_1] run function animated_java:scp1499_1/animations/point/stop
attribute @n[tag=scp1499_1origin] movement_speed modifier remove 1499-1-0-0-0