# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tellraw @a ["",[[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"m4a1",")"]," -> "],{"text":"ERROR: ","color":"red"},"\n "],{"text":"No variants are available.","color":"red"},["\n"]]
function animated_java:m4a1/remove/this