# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.elevator_doors.root] run return 0
execute if entity @s[tag=aj.elevator_doors.animation.openclose.playing] run function animated_java:elevator_doors/animations/openclose/zzz/on_tick
execute on passengers run rotate @s ~ ~