# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '0951dbc9a85e2823e8f328dcade123da00fd80d4353e9cea72468e4ba501bfe0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack