# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:lever/animations/pause_all
tag @s add aj.lever.animation.switch.playing
scoreboard players set @s aj.switch.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:lever/animations/switch/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only