# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp939 rig_hash set value '6af42e31c440b1e6a7bf4e49bd723798455eb651291f8a7f3088cff77d2aa625'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.run.frame dummy