# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp939 rig_hash set value 'a938a85b81e80d108726b6ca9179bbebe9e7cb2f127d38028028aa85762d089f'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.attack.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.run.frame dummy