# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:ci rig_hash set value 'f729715992c40e51338298c359579b3e1370cbe2740820c5e6b0aa324aac2a0a'
scoreboard objectives add aj.walk.frame dummy