# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers1_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers0_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers1_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers0_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers1_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_fingers0_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_arm0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_arm0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers1_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers0_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers1_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers0_0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers1_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_fingers0_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_arm0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_arm0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_leg0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_leg0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_leg0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_leg0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out