# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.mouth] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mouth set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.neck] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_neck set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.chest] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_chest set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers1_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers0_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers1_0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers0_0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers1_1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers1_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_fingers0_1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_fingers0_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_arm0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_arm0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers1_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers0_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers1_0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers0_0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers1_2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers1_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_fingers0_2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_fingers0_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_hand] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_hand set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_arm0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_arm0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_foot set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_leg0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_leg0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.r_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_foot] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_foot set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_leg0] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_leg0 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.l_leg] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_leg set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.scp096.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out