# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door_check0.root] run return 0
execute on passengers if entity @s[tag=aj.door_check0.data] unless data entity @s {data:{rigHash: '080e4f8ef885b367b381d641e2049ea597191df791cd716ffa620833e73761bb'}} on vehicle run function animated_java:door_check0/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1