# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9992f,0.0216f,0.0325f,0f,0.0162f,0.9876f,-0.1564f,0.6413f,-0.0355f,-0.1558f,-0.9872f,0.0244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0875f,0.0091f,-0.0947f,0f,0.0033f,1.0896f,0.0668f,0.2625f,0.0951f,0.0662f,-1.0855f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9868f,-0.0803f,-0.1407f,0.1231f,-0.1057f,0.9774f,0.1833f,0.575f,0.1228f,0.1957f,-0.9729f,-0.0142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9959f,0.0812f,0.041f,-0.1281f,0.0883f,0.971f,0.2221f,0.575f,-0.0218f,0.2248f,-0.9742f,0.0054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound cb:scp1048a.death block @a ~ ~1 ~ 2 1 1