# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9992f,0.0216f,0.0325f,0f,0.0162f,0.9876f,-0.1564f,0.65f,-0.0355f,-0.1558f,-0.9872f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0958f,0f,-0.0959f,0f,0.0033f,1.0993f,-0.0382f,0.2625f,0.0958f,-0.0384f,-1.0951f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.977f,-0.0461f,-0.2084f,0.1219f,-0.0465f,0.9989f,-0.003f,0.575f,0.2083f,0.0068f,-0.978f,-0.0187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9972f,0.0347f,0.0667f,-0.1281f,0.0348f,0.9994f,0.0001f,0.575f,-0.0667f,0.0024f,-0.9978f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

particle block{block_state:{Name:redstone_block}} ~ ~0.5 ~ 0 0.2 0 0 100
# particle minecraft:crit ~ ~0.5 ~ 0 0.2 0 0.35 100 force

tp @n[tag=scp1048Aorigin] 0 32 0
tp @s 0 -32 0

execute positioned 0 32 0 run function scp1048a:despawn