# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9992f,0.0216f,0.0325f,0f,0.0162f,0.9876f,-0.1564f,0.6041f,-0.0355f,-0.1558f,-0.9872f,0.1943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1.0878f,0.0459f,-0.0833f,0f,0.0033f,0.974f,0.4936f,0.2625f,0.0951f,0.4914f,-0.9704f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9086f,-0.3787f,-0.1763f,0.1612f,-0.3397f,0.4242f,0.8395f,0.575f,-0.2431f,0.8226f,-0.514f,0.1321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9369f,0.2663f,0.2266f,-0.1281f,0.3065f,0.3135f,0.8988f,0.575f,0.1683f,0.9115f,-0.3753f,0.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

playsound cb:scp1048a.shriek ambient @a ~ ~0.75 ~ 10 1 1
scoreboard players set @n[tag=scp1048Aorigin] shriek 0