# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door914.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door914', 'function_path': 'animated_java:door914/animations/open/next_frame'}
execute if score @s aj.open.frame matches 31.. run scoreboard players set @s aj.open.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.open.frame
execute at @s run function animated_java:door914/animations/open/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.open.frame 1