# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:door914/animations/pause_all
tag @s add aj.door914.animation.open.playing
scoreboard players set @s aj.open.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:door914/animations/open/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only