# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door914.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door914', 'function_path': 'animated_java:door914/animations/open/play'}
tag @s add aj.door914.animation.open.playing
scoreboard players set @s aj.open.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:door914/animations/open/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only