# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '99ccd92d9dea492c1cf68bf926b5ff7126826333caf6d60bd0759999a1e036a2'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack