# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'c8ea99859b9c49a37627ca380e504733c29543e85d485dd0d71ff6bdf9003806'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack