# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp1048.root] run return 0
execute if entity @s[tag=aj.scp1048.animation.walk.playing] run function animated_java:scp1048/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.scp1048.animation.idle.playing] run function animated_java:scp1048/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp1048.animation.greet.playing] run function animated_java:scp1048/animations/greet/zzz/on_tick
execute on passengers run rotate @s ~ ~