# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp066/animations/pause_all
tag @s add aj.scp066.animation.wallow.playing
scoreboard players set @s aj.wallow.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp066/animations/wallow/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only