# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:guard rig_hash set value 'b2b1078dd233e0fa7e9e7656733941278d02fc6e3c35a8e54afaf6fb097fbb75'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.walk2.frame dummy