# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:guard rig_hash set value 'cbed8388c5e899940af3be21f27a4a0a07957b20146d511b10fcab884bfcde46'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.idle2.frame dummy
scoreboard objectives add aj.walk2.frame dummy
scoreboard objectives add aj.paper.frame dummy