# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp096 rig_hash set value 'b1ab7207065af6d91bf7f5835edd8d3b123eec0d96d763d614e6992146a06033'
scoreboard objectives add aj.idle_sit.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.rage_in.frame dummy
scoreboard objectives add aj.attack_basic.frame dummy
scoreboard objectives add aj.run.frame dummy