# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle_sit.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.rage_in.frame dummy
scoreboard objectives add aj.attack_basic.frame dummy
scoreboard objectives add aj.run.frame dummy
scoreboard objectives add aj.run_.frame dummy
scoreboard objectives add aj.idle_sit_.frame dummy
scoreboard objectives add aj.idle_.frame dummy
scoreboard objectives add aj.rage_in_.frame dummy
scoreboard objectives add aj.attack_basic_.frame dummy