# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle_sit.frame
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.rage_in.frame
scoreboard objectives remove aj.attack_basic.frame
scoreboard objectives remove aj.run.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:scp096)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'scp096'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']