# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle_sit.frame
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.rage_in.frame
scoreboard objectives remove aj.attack_basic.frame
scoreboard objectives remove aj.run.frame
scoreboard objectives remove aj.run_.frame
scoreboard objectives remove aj.idle_sit_.frame
scoreboard objectives remove aj.idle_.frame
scoreboard objectives remove aj.rage_in_.frame
scoreboard objectives remove aj.attack_basic_.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"scp096",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]