# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9d01aaabec093b797c6fe8afd02de3dc0d2f210c1358fc3b6fc6826049c6e5a7'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack