# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '42186dac4257e5a9785ba0d97645d0a5870a4b5c4e02383d4f20c54f48b457f0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack