# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0312f,0f,0.9999f,0.0114f,2.311f,0f,0.0114f,-0.9999f,0.1633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-1f,0f,0f,0.0312f,0f,1f,0.0047f,2.2173f,0f,0.0047f,-1f,0.1473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_2) {transformation: [-0.9956f,-0.0931f,0.0078f,-0.2634f,-0.0934f,0.9899f,-0.1066f,0.3144f,0.0022f,-0.1069f,-0.9943f,0.0778f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_2) {transformation: [-0.9968f,-0.0798f,0.0078f,-0.2733f,-0.0801f,0.9911f,-0.1066f,0.4382f,0.0008f,-0.1069f,-0.9943f,0.0645f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_0) {transformation: [-0.9965f,-0.0831f,0.0078f,-0.2648f,-0.0835f,0.9908f,-0.1066f,0.3277f,0.0011f,-0.1069f,-0.9943f,0.2021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_0) {transformation: [-0.997f,-0.0764f,0.0078f,-0.2743f,-0.0768f,0.9913f,-0.1066f,0.4516f,0.0004f,-0.1069f,-0.9943f,0.1887f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_1) {transformation: [-0.9968f,-0.0798f,0.0078f,-0.2651f,-0.0801f,0.9911f,-0.1066f,0.3209f,0.0008f,-0.1069f,-0.9943f,0.14f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_1) {transformation: [-0.9975f,-0.0697f,0.0078f,-0.2738f,-0.0702f,0.9918f,-0.1066f,0.4449f,-0.0003f,-0.1069f,-0.9943f,0.1266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_hand) {transformation: [-0.9975f,-0.0697f,0.0078f,-0.2913f,-0.0702f,0.9918f,-0.1066f,0.6929f,-0.0003f,-0.1069f,-0.9943f,0.0999f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm0) {transformation: [-0.9984f,-0.0563f,0.0078f,-0.3335f,-0.0568f,0.9927f,-0.1066f,1.4374f,-0.0017f,-0.1069f,-0.9943f,0.0197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.9996f,0.0259f,0.0074f,-0.3125f,0.0257f,0.9995f,-0.0156f,2.2495f,-0.0078f,-0.0154f,-0.9999f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_1) {transformation: [-0.9958f,0.0879f,-0.0236f,0.313f,0.0903f,0.9871f,-0.1319f,0.3259f,0.0117f,-0.1334f,-0.991f,0.1842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_1) {transformation: [-0.9966f,0.0786f,-0.0236f,0.3229f,0.081f,0.988f,-0.1319f,0.4494f,0.013f,-0.1333f,-0.991f,0.1676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_0) {transformation: [-0.9951f,0.0959f,-0.0236f,0.3134f,0.0982f,0.9864f,-0.1319f,0.3343f,0.0107f,-0.1335f,-0.991f,0.2462f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_0) {transformation: [-0.9959f,0.0873f,-0.0236f,0.3243f,0.0896f,0.9872f,-0.1319f,0.4577f,0.0118f,-0.1334f,-0.991f,0.2295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_2) {transformation: [-0.9955f,0.0919f,-0.0236f,0.3111f,0.0943f,0.9868f,-0.1319f,0.3177f,0.0112f,-0.1335f,-0.991f,0.1223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_2) {transformation: [-0.9964f,0.0819f,-0.0236f,0.3214f,0.0843f,0.9877f,-0.1319f,0.4412f,0.0125f,-0.1334f,-0.991f,0.1056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_hand) {transformation: [-0.997f,0.0739f,-0.0236f,0.3413f,0.0764f,0.9883f,-0.1319f,0.6965f,0.0136f,-0.1333f,-0.991f,0.1342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm0) {transformation: [-0.9966f,0.0739f,-0.037f,0.3968f,0.0781f,0.9883f,-0.1308f,1.4377f,0.0269f,-0.1333f,-0.9907f,0.0344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.9996f,-0.0268f,0.0011f,0.375f,-0.0268f,0.9991f,-0.0335f,2.2495f,-0.0002f,-0.0336f,-0.9994f,0.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_foot) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0006f,0.0464f,0f,-0.0006f,-1f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg0) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0.0034f,0.687f,0f,0.0034f,-1f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0034f,1.312f,0f,-0.0034f,-1f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_foot) {transformation: [-1f,0f,0f,0.1875f,0f,1f,-0.001f,0.0464f,0f,-0.001f,-1f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg0) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0.0034f,0.687f,0f,0.0034f,-1f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.1875f,0f,1f,-0.0034f,1.312f,0f,-0.0034f,-1f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.25f,0f,1f,0.0067f,1.187f,0f,0.0067f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

tag @n[tag=aj.scp096.root] add raging_in