# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0312f,0f,0.9994f,-0.0349f,2.2353f,0f,-0.0349f,-0.9994f,0.334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-1f,0f,0f,0.0312f,0f,0.9976f,0.0698f,2.1429f,0f,0.0698f,-0.9976f,0.3119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_2) {transformation: [-0.8607f,-0.3647f,-0.3553f,-0.3621f,0.4468f,-0.2066f,-0.8704f,2.2264f,0.2441f,-0.9079f,0.3408f,2.1392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_2) {transformation: [-0.9257f,-0.1296f,-0.3553f,-0.3783f,0.3781f,-0.3152f,-0.8704f,2.1871f,0.0008f,-0.9401f,0.3408f,2.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_0) {transformation: [-0.9192f,-0.1698f,-0.3553f,-0.3279f,0.3915f,-0.2984f,-0.8704f,2.3392f,0.0418f,-0.9392f,0.3408f,2.0962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_0) {transformation: [-0.9335f,-0.0484f,-0.3553f,-0.3339f,0.3492f,-0.3469f,-0.8704f,2.2959f,-0.0811f,-0.9366f,0.3408f,1.9791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_1) {transformation: [-0.9109f,-0.2097f,-0.3553f,-0.3552f,0.4042f,-0.281f,-0.8704f,2.2867f,0.0827f,-0.9365f,0.3408f,2.1169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_1) {transformation: [-0.9347f,-0.0076f,-0.3553f,-0.3561f,0.3338f,-0.3618f,-0.8704f,2.2415f,-0.1219f,-0.9322f,0.3408f,2.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_hand) {transformation: [-0.9318f,0.0739f,-0.3553f,-0.3376f,0.301f,-0.3895f,-0.8704f,2.1441f,-0.2027f,-0.918f,0.3408f,1.7709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm0) {transformation: [-0.9289f,-0.0331f,-0.3689f,-0.3625f,0.3696f,-0.0168f,-0.929f,2.1315f,0.0246f,-0.9993f,0.0278f,1.0214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.9097f,0.0615f,-0.4108f,-0.3125f,0.4148f,0.0839f,-0.906f,2.1997f,-0.0212f,-0.9946f,-0.1019f,0.2133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_1) {transformation: [-0.4639f,-0.1431f,0.8743f,0.6032f,-0.8776f,0.2093f,-0.4314f,1.9803f,-0.1213f,-0.9673f,-0.2227f,2.1151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_1) {transformation: [-0.443f,-0.1986f,0.8743f,0.5784f,-0.8965f,0.1008f,-0.4314f,1.9929f,-0.0025f,-0.9749f,-0.2227f,1.9932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_0) {transformation: [-0.4763f,-0.0938f,0.8743f,0.5421f,-0.8509f,0.2999f,-0.4314f,1.9946f,-0.2217f,-0.9493f,-0.2227f,2.1282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_0) {transformation: [-0.4626f,-0.1471f,0.8743f,0.5237f,-0.8793f,0.2017f,-0.4314f,2.0198f,-0.1128f,-0.9683f,-0.2227f,2.0071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_2) {transformation: [-0.4707f,-0.1186f,0.8743f,0.6554f,-0.8654f,0.255f,-0.4314f,1.9484f,-0.1717f,-0.9596f,-0.2227f,2.101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_2) {transformation: [-0.4512f,-0.1791f,0.8743f,0.633f,-0.8913f,0.1398f,-0.4314f,1.9659f,-0.045f,-0.9739f,-0.2227f,1.9793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_hand) {transformation: [-0.43f,-0.2252f,0.8743f,0.5221f,-0.901f,0.0459f,-0.4314f,2.0043f,0.057f,-0.9732f,-0.2227f,1.7499f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm0) {transformation: [-0.5557f,-0.0675f,-0.8287f,0.4853f,0.8284f,0.0391f,-0.5587f,2.0355f,0.0701f,-0.997f,0.0342f,1.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.8985f,-0.1358f,0.4174f,0.375f,-0.4375f,0.2021f,-0.8762f,2.1997f,0.0346f,-0.9699f,-0.241f,0.2133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_foot) {transformation: [-1f,0f,0f,-0.125f,0f,1f,-0.0087f,0.0257f,0f,-0.0087f,-1f,-0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg0) {transformation: [-1f,0f,0f,-0.125f,0f,0.9994f,0.0349f,0.6659f,0f,0.0349f,-0.9994f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9986f,-0.0523f,1.29f,0f,-0.0523f,-0.9986f,-0.0135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_foot) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.0286f,0f,0f,-1f,0.074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg0) {transformation: [-1f,0f,0f,0.1875f,0f,0.9997f,-0.0262f,0.6691f,0f,-0.0262f,-0.9997f,0.0572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.1875f,0f,0.9936f,-0.1132f,1.29f,0f,-0.1132f,-0.9936f,-0.0135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.25f,0f,0.9703f,0.2419f,1.1688f,0f,0.2419f,-0.9703f,-0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

tag @n[tag=aj.scp096.root] remove raging_in
tag @n[tag=aj.scp096.root] add in_rage
execute as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/rage_in_/stop
execute as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/run_/play