# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scp1499_1.animation.idle.playing
tag @s remove aj.scp1499_1.animation.walk.playing
tag @s remove aj.scp1499_1.animation.attack.playing
tag @s remove aj.scp1499_1.animation.point.playing