# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:door914 rig_hash set value 'c5e3b819b621b6dec826d779a32f6d690370447c22b1f290335ac46e42fd0a21'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy