# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp650 rig_hash set value 'b40e3534e9b2574a3677181973bdc080f63490e1484affa0437c974f0276e876'
scoreboard objectives add aj.switch.frame dummy