# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_right_leg) {transformation: [-0.998f,0.0349f,0.0523f,-0.1312f,0.0349f,0.9994f,-0.0018f,0.5f,-0.0523f,0f,-0.9986f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.9992f,-0.0175f,-0.0349f,0.125f,-0.0174f,0.9998f,-0.0006f,0.5f,0.0349f,0f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=guardaj] run function animated_java:guard/animations/walk2/stop