# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '06a952b8b325aa3e70e4ad77ccd093d1ec7a8a2911f982854743c248d8baddf7'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack