# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.5677f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,-0.4587f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

tag @n[tag=singledoor1] add closed
tag @n[tag=singledoor1] add proceed
playsound cb:door1.open ambient @a[distance=..20] ~ ~1 ~ 1.25 1 1
execute as @n[tag=singledoor1, tag=storage939door] run playsound cb:door1.open_dist ambient @a[distance=20..64] ~ ~ ~ 5 1 1