# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-1.3807f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.0363f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[type=item_display, tag=singledoor1, tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r0] at @s run setblock ~-1 ~ ~ minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r0] at @s run setblock ~ ~1 ~ minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r0] at @s run setblock ~ ~ ~ minecraft:air

execute as @n[type=item_display, tag=singledoor1, tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r1] at @s run setblock ~ ~ ~-1 minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r1] at @s run setblock ~ ~1 ~ minecraft:air
execute as @n[type=item_display, tag=singledoor1, tag=r1] at @s run setblock ~ ~ ~ minecraft:air