# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-2.1937f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,0.5313f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=singledoor1] run function animated_java:singledoor1/animations/open_close_toggle/pause
tag @n[tag=singledoor1] remove proceed
tag @n[tag=singledoor1] remove closed
tag @n[tag=singledoor1] add opened