# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wing0) {transformation: [-2f,0f,0f,-0.5f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wing1) {transformation: [-2f,0f,0f,-0.5f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

tag @n[tag=singledoor1] remove proceed
tag @n[tag=singledoor1] remove opened
tag @n[tag=singledoor1] add closed

execute as @n[tag=singledoor1] run function animated_java:singledoor1/animations/open_close_toggle/stop