# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.914_start.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': '914_start', 'function_path': 'animated_java:914_start/animations/start/next_frame'}
execute if score @s aj.start.frame matches 24.. run scoreboard players set @s aj.start.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.start.frame
execute at @s run function animated_java:914_start/animations/start/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.start.frame 1