# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.scientist.node.r_arm] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_r_arm
execute on passengers if entity @s[tag=aj.scientist.node.body] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_body
execute on passengers if entity @s[tag=aj.scientist.node.head] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_head
execute on passengers if entity @s[tag=aj.scientist.node.r_leg] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_r_leg
execute on passengers if entity @s[tag=aj.scientist.node.l_arm] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_l_arm
execute on passengers if entity @s[tag=aj.scientist.node.l_leg] at @s run function animated_java:scientist/variants/default/zzz/apply_to_node_l_leg
return 1