# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.gate.root] run return 0
execute on passengers if entity @s[tag=aj.gate.data] unless data entity @s {data:{rigHash: 'c6583762bce3411eb186433822353b7cadffa0df7588279ad6f787e06b0a2a14'}} on vehicle run function animated_java:gate/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1