# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door1.open ambient @a[distance=..24] ~ ~ ~ 1 1 1
tag @n[tag=door_marker_hcz] add opened
tag @n[tag=door_marker_hcz] remove closed
scoreboard players operation @n[tag=door_marker_hcz,tag=!uninteractable] door_interact_cd = max_hcz door_interact_cd
execute as @n[tag=door_marker_hcz,tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:lightning_rod[facing=east]
execute as @n[tag=door_marker_hcz,tag=r0] at @s run setblock ~-1 ~ ~ minecraft:lightning_rod[facing=east]
execute as @n[tag=door_marker_hcz,tag=r0] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=east]
execute as @n[tag=door_marker_hcz,tag=r0] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=east]
execute as @n[tag=door_marker_hcz,tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:lightning_rod[facing=north]
execute as @n[tag=door_marker_hcz,tag=r1] at @s run setblock ~ ~ ~-1 minecraft:lightning_rod[facing=north]
execute as @n[tag=door_marker_hcz,tag=r1] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=north]
execute as @n[tag=door_marker_hcz,tag=r1] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=north]

execute if entity @n[tag=door_marker_hcz,tag=r0] as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker_hcz,tag=r0] positioned ~0.5 ~ ~ as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker_hcz,tag=r0] positioned ~-0.5 ~ ~ as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker_hcz,tag=r1] as @a[distance=..0.5] run tp @s ~0.5 ~ ~
execute if entity @n[tag=door_marker_hcz,tag=r1] positioned ~ ~ ~0.5 as @a[distance=..0.5] run tp @s ~0.5 ~ ~
execute if entity @n[tag=door_marker_hcz,tag=r1] positioned ~ ~ ~-0.5 as @a[distance=..0.5] run tp @s ~0.5 ~ ~