# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.m4a1.root] run return 0
execute on passengers if entity @s[tag=aj.m4a1.data] unless data entity @s {data:{rigHash: 'd3d2dc020d595c15d577edaac7c9e27160ad60963fd38c5d17b239fb4b166e8d'}} on vehicle run function animated_java:m4a1/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1