# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.866f,0.5f,0.3906f,0f,0.5f,-0.866f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.989f,-0.1478f,0.3938f,0f,-0.1478f,-0.989f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0032f,1.6868f,0f,0.0032f,-1f,-0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9819f,0.1893f,0.9278f,0f,0.1893f,-0.9819f,-0.1256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.0317f,-0.9995f,1.5583f,0f,-0.9995f,-0.0317f,-0.1428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9995f,-0.0317f,1f,0f,-0.0317f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}