# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.8904f,0.4551f,0.3917f,0f,0.4551f,-0.8904f,-0.1654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9929f,-0.1188f,0.3766f,0f,-0.1188f,-0.9929f,0.1159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6866f,0f,0f,-1f,-0.0365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9781f,0.2079f,0.9264f,0f,0.2079f,-0.9781f,-0.1381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.0175f,-0.9998f,1.5578f,0f,-0.9998f,-0.0175f,-0.1446f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9994f,-0.0349f,1f,0f,-0.0349f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}