# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9643f,0.2648f,0.3962f,0f,0.2648f,-0.9643f,-0.077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9971f,0.0766f,0.3672f,0f,0.0766f,-0.9971f,0.0294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.011f,1.6862f,0f,0.011f,-0.9999f,-0.016f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9888f,0.1495f,0.9006f,0f,0.1495f,-0.9888f,-0.0862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.1564f,-0.9877f,1.5616f,0f,-0.9877f,-0.1564f,-0.1289f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.007f,1f,0f,-0.007f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}