# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9901f,-0.1404f,0.4051f,0f,-0.1404f,-0.9901f,0.0998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.8676f,0.4973f,0.388f,0f,0.4973f,-0.8676f,-0.1773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.6797f,0f,0f,-1f,-0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9744f,-0.225f,0.9358f,0f,-0.225f,-0.9744f,0.1304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.0175f,-0.9998f,1.5578f,0f,-0.9998f,-0.0175f,-0.1446f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9994f,-0.0349f,1f,0f,-0.0349f,-0.9994f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}