# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9816f,-0.1908f,0.4063f,0f,-0.1908f,-0.9816f,0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.8387f,0.5446f,0.3906f,0f,0.5446f,-0.8387f,-0.2031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0069f,1.6811f,0f,0.0069f,-1f,-0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9799f,-0.1994f,0.9042f,0f,-0.1994f,-0.9799f,0.129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.061f,-0.9981f,1.5614f,0f,-0.9981f,-0.061f,-0.1299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0087f,1f,0f,-0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}