# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9911f,-0.1334f,0.3853f,0f,-0.1334f,-0.9911f,0.1063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.887f,0.4617f,0.388f,0f,0.4617f,-0.887f,-0.1693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0138f,1.6813f,0f,0.0138f,-0.9999f,0.0056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9848f,-0.1736f,0.8728f,0f,-0.1736f,-0.9848f,0.1259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.1045f,-0.9945f,1.5646f,0f,-0.9945f,-0.1045f,-0.1152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,1f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute at @n[tag=scp049] run function animated_java:scp049/animations/walk/zzz/frames/25_root_commands