# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9993f,-0.0378f,0.3697f,0f,-0.0378f,-0.9993f,0.0453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9816f,0.1908f,0.3802f,0f,0.1908f,-0.9816f,-0.0677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0055f,1.685f,0f,0.0055f,-1f,0.0023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9976f,-0.0698f,0.9121f,0f,-0.0698f,-0.9976f,0.0506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.1461f,-0.9893f,1.5634f,0f,-0.9893f,-0.1461f,-0.1211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.007f,1f,0f,0.007f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}