# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9998f,-0.0189f,0.3723f,0f,-0.0189f,-0.9998f,0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9954f,0.0958f,0.3776f,0f,0.0958f,-0.9954f,-0.0339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0028f,1.6863f,0f,0.0028f,-1f,0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9994f,-0.0349f,0.9249f,0f,-0.0349f,-0.9994f,0.0254f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.1599f,-0.9871f,1.5629f,0f,-0.9871f,-0.1599f,-0.123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0035f,1f,0f,0.0035f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}