# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9135f,0.4067f,0.3875f,0f,0.4067f,-0.9135f,-0.15f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.993f,-0.1184f,0.392f,0f,-0.1184f,-0.993f,0.1131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0095f,1.687f,0f,0.0095f,-1f,-0.0265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9884f,0.1517f,0.9304f,0f,0.1517f,-0.9884f,-0.1005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.0603f,-0.9982f,1.5591f,0f,-0.9982f,-0.0603f,-0.1392f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9997f,-0.0254f,1f,0f,-0.0254f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}