# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.891f,0.454f,0.3891f,0f,0.454f,-0.891f,-0.1687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9911f,-0.1331f,0.3933f,0f,-0.1331f,-0.9911f,0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0063f,1.6869f,0f,0.0063f,-1f,-0.0299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.4938f,0f,0.9854f,0.1705f,0.9291f,0f,0.1705f,-0.9854f,-0.1131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1f,0f,0f,-0.3062f,0f,0.046f,-0.9989f,1.5587f,0f,-0.9989f,-0.046f,-0.141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9996f,-0.0286f,1f,0f,-0.0286f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}