# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'c5e3b819b621b6dec826d779a32f6d690370447c22b1f290335ac46e42fd0a21'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack