# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '865d6e23fa7590b080248d1c873a2e86f3c6e360ae70330f74780a1e15569184'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack