# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp049_2 rig_hash set value 'b544adb38d285199ab6c5749f085b33795fb0204dc411182b8a091384ef30ef8'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.attack.frame dummy