# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door.checkpoint ambient @a[distance=..24] ~ ~2 ~ 1.75 1 1
playsound cb:interact.card ambient @a[distance=..24] ~ ~ ~ 2 1 1

tag @n[tag=door_marker_checkpoint] add opened
tag @n[tag=door_marker_checkpoint] remove closed

scoreboard players operation @n[tag=door_marker_checkpoint] door_interact_cd = max door_interact_cd
scoreboard players operation @n[tag=door_marker_checkpoint] door_checkpoint_timer = max door_checkpoint_timer

execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~1 ~ minecraft:lightning_rod[facing=west]