# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door.checkpoint ambient @a[distance=..24] ~ ~2 ~ 1.75 1 1
playsound cb:interact.card ambient @a[distance=..24] ~ ~ ~ 2 1 1
tag @n[tag=door_marker_check0] add opened
tag @n[tag=door_marker_check0] remove closed
scoreboard players operation @n[tag=door_marker_check0] door_interact_cd = max door_interact_cd
execute at @n[tag=door_marker_check0] run setblock ~-1 ~ ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~-1 ~1 ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~-2 ~ ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~-2 ~1 ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~2 ~ ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~2 ~1 ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~3 ~ ~ minecraft:lightning_rod
execute at @n[tag=door_marker_check0] run setblock ~3 ~1 ~ minecraft:lightning_rod