# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~ ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~ ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~ ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~ ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~1 ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~1 ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~1 ~ air
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~1 ~ air