# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @n[tag=door_marker_check0] run setblock ~-1 ~ ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~-1 ~1 ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~-2 ~ ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~-2 ~1 ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~2 ~ ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~2 ~1 ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~3 ~ ~ minecraft:air
execute at @n[tag=door_marker_check0] run setblock ~3 ~1 ~ minecraft:air