# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-4f,0f,0f,3.9999f,0f,4f,0f,0f,0f,0f,-4f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-4f,0f,0f,0.0001f,0f,4f,0f,0f,0f,0f,-4f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:door_check0/animations/openclosetoggle/zzz/frames/36_root_commands