# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door.checkpoint ambient @a[distance=..24] ~ ~2 ~ 1.75 1 1
# playsound cb:interact.card ambient @a[distance=..24] ~ ~ ~ 2 1 1

tag @n[tag=door_marker_checkpoint] add closed
tag @n[tag=door_marker_checkpoint] remove opened

scoreboard players operation @n[tag=door_marker_checkpoint] door_interact_cd = max door_interact_cd