# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~ ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~1 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~2 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-2 ~1 ~ minecraft:lightning_rod[facing=west]
execute at @n[tag=door_marker_checkpoint] run setblock ~-3 ~1 ~ minecraft:lightning_rod[facing=west]

# execute at @n[tag=door_marker_checkpoint] positioned ~-1.5 ~ ~ run tp @a[distance=..0.5] ~-0.25 ~ ~0.5
# execute at @n[tag=door_marker_checkpoint] positioned ~-2.25 ~ ~ run tp @a[distance=..0.5] ~-0.25 ~ ~0.5
# execute at @n[tag=door_marker_checkpoint] positioned ~1.5 ~ ~ run tp @a[distance=..0.5] ~0.25 ~ ~0.5
# execute at @n[tag=door_marker_checkpoint] positioned ~2.25 ~ ~ run tp @a[distance=..0.5] ~0.25 ~ ~0.5