# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:celldoor/animations/pause_all
tag @s add aj.celldoor.animation.openclose.playing
scoreboard players set @s aj.openclose.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:celldoor/animations/openclose/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only