# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0.0312f,0f,10f,0f,2.4096f,0f,0f,-1f,0.5125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_foot) {transformation: [-1f,0f,0f,-0.125f,0f,0.5592f,0.829f,0.433f,0f,0.829f,-0.5592f,-0.6013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg0) {transformation: [-1f,0f,0f,-0.125f,0f,0.4067f,0.9135f,0.6935f,0f,0.9135f,-0.4067f,-0.0161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9986f,0.0523f,1.3114f,0f,0.0523f,-0.9986f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_foot) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.0482f,0f,0f,-1f,-0.0395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg0) {transformation: [-1f,0f,0f,0.1875f,0f,0.9962f,0.0872f,0.6864f,0f,0.0872f,-0.9962f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,1.3114f,0f,0f,-1f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}