# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:singledoor1/animations/pause_all
tag @s add aj.singledoor1.animation.open_close_toggle.playing
scoreboard players set @s aj.open_close_toggle.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:singledoor1/animations/open_close_toggle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only