# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.scp096.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'scp096', 'function_path': 'animated_java:scp096/animations/run_/next_frame'}
execute if score @s aj.run_.frame matches 209.. run scoreboard players set @s aj.run_.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.run_.frame
execute at @s run function animated_java:scp096/animations/run_/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.run_.frame 1