# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.scp096.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'scp096', 'function_path': 'animated_java:scp096/animations/run_/stop'}
tag @s remove aj.scp096.animation.run_.playing
scoreboard players set @s aj.run_.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp096/animations/run_/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @n[tag=aj.scp096.root] remove in_rage
execute as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/idle_sit_/play