# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0.0312f,0f,10f,0f,2.4375f,0f,0f,-1f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0312f,0f,1f,0f,2.3125f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-1f,0f,0f,0.0312f,0f,1f,0f,2.2188f,0f,0f,-1f,0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chest) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_2) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2663f,-0.1304f,0.9905f,-0.0436f,0.3163f,0.0076f,-0.043f,-0.999f,0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_2) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2826f,-0.1304f,0.9905f,-0.0436f,0.4401f,0.0076f,-0.043f,-0.999f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_0) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2661f,-0.1304f,0.9905f,-0.0436f,0.3218f,0.0076f,-0.043f,-0.999f,0.1466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_0) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2824f,-0.1304f,0.9905f,-0.0436f,0.4456f,0.0076f,-0.043f,-0.999f,0.1412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_1) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2662f,-0.1304f,0.9905f,-0.0436f,0.319f,0.0076f,-0.043f,-0.999f,0.0841f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_1) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2825f,-0.1304f,0.9905f,-0.0436f,0.4428f,0.0076f,-0.043f,-0.999f,0.0788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_hand) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.3152f,-0.1304f,0.9905f,-0.0436f,0.6905f,0.0076f,-0.043f,-0.999f,0.068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm0) {transformation: [-0.999f,-0.0437f,-0.0019f,-0.3479f,-0.0435f,0.9981f,-0.0436f,1.439f,0.0038f,-0.0435f,-0.999f,0.0354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.999f,0.0436f,-0.0019f,-0.3125f,0.0436f,0.9981f,-0.0436f,2.25f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_1) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_1) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_0) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.3125f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_0) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.4375f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_2) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.3125f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_2) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.4375f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_hand) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm0) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.4375f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1f,0f,0f,0.375f,0f,1f,0f,2.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_foot) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.0469f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg0) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_foot) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.0469f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg0) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/run/stop