# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_mouth) {transformation: [-1f,0f,0f,0.0312f,0f,8.1915f,0.5736f,2.2853f,0f,5.7358f,-0.8192f,0.4232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0.0312f,0f,0.8192f,0.5736f,2.3084f,0f,0.5736f,-0.8192f,0.1723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_neck) {transformation: [-1f,0f,0f,0.0312f,0f,0.9848f,0.1736f,2.2188f,0f,0.1736f,-0.9848f,0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_chest) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_2) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2663f,-0.1304f,0.9905f,-0.0436f,0.3163f,0.0076f,-0.043f,-0.999f,0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_2) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2826f,-0.1304f,0.9905f,-0.0436f,0.4401f,0.0076f,-0.043f,-0.999f,0.0163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_0) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2661f,-0.1304f,0.9905f,-0.0436f,0.3218f,0.0076f,-0.043f,-0.999f,0.1466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_0) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2824f,-0.1304f,0.9905f,-0.0436f,0.4456f,0.0076f,-0.043f,-0.999f,0.1412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers1_1) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2662f,-0.1304f,0.9905f,-0.0436f,0.319f,0.0076f,-0.043f,-0.999f,0.0841f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_fingers0_1) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.2825f,-0.1304f,0.9905f,-0.0436f,0.4428f,0.0076f,-0.043f,-0.999f,0.0788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_hand) {transformation: [-0.9914f,-0.1306f,-0.0019f,-0.3152f,-0.1304f,0.9905f,-0.0436f,0.6905f,0.0076f,-0.043f,-0.999f,0.068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm0) {transformation: [-0.999f,-0.0437f,-0.0019f,-0.3479f,-0.0435f,0.9981f,-0.0436f,1.439f,0.0038f,-0.0435f,-0.999f,0.0354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.999f,0.0436f,-0.0019f,-0.3125f,0.0436f,0.9981f,-0.0436f,2.25f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_1) {transformation: [-0.9797f,0.1976f,0.0322f,0.2371f,0.1988f,0.9793f,0.0391f,0.2295f,-0.0238f,0.0447f,-0.9987f,-0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_1) {transformation: [-0.9797f,0.1976f,0.0322f,0.2619f,0.1988f,0.9793f,0.0391f,0.3519f,-0.0238f,0.0447f,-0.9987f,-0.0138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_0) {transformation: [-0.9797f,0.1976f,0.0322f,0.2351f,0.1988f,0.9793f,0.0391f,0.227f,-0.0238f,0.0447f,-0.9987f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_0) {transformation: [-0.9797f,0.1976f,0.0322f,0.2598f,0.1988f,0.9793f,0.0391f,0.3494f,-0.0238f,0.0447f,-0.9987f,0.0486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers1_2) {transformation: [-0.9797f,0.1976f,0.0322f,0.2392f,0.1988f,0.9793f,0.0391f,0.2319f,-0.0238f,0.0447f,-0.9987f,-0.0818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_fingers0_2) {transformation: [-0.9797f,0.1976f,0.0322f,0.2639f,0.1988f,0.9793f,0.0391f,0.3543f,-0.0238f,0.0447f,-0.9987f,-0.0762f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_hand) {transformation: [-0.9797f,0.1976f,0.0322f,0.3113f,0.1988f,0.9793f,0.0391f,0.5967f,-0.0238f,0.0447f,-0.9987f,-0.0026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm0) {transformation: [-0.999f,0.0453f,-0.0055f,0.3452f,0.0455f,0.998f,-0.0439f,1.3452f,0.0035f,-0.0441f,-0.999f,-0.0357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.999f,-0.0403f,-0.0167f,0.3125f,-0.041f,0.9982f,0.0433f,2.1563f,0.0149f,0.0439f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_foot) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.0469f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg0) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_foot) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.0469f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg0) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,0.6875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-1f,0f,0f,0.1875f,0f,1f,0f,1.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0.25f,0f,1f,0f,1.1875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}


execute as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/attack_basic/stop
execute as @a[tag=!dead] if entity @s[tag=triggered096] as @n[tag=aj.scp096.root] run function animated_java:scp096/animations/run/play