# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_cap) {transformation: [-1.1119f,0f,0f,1.0342f,0f,1.1119f,0f,1.1945f,0f,0f,-1.1119f,0.242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

tag @n[tag=aj.scp008.root] add closed
tag @n[tag=aj.scp008.root] remove opened

execute as @e[tag=checkpoint, tag=ez] run tag @s remove blocked