# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'e1a5fffdb294055682148cb5dc8dca55a3f49863917db8b23ce9d0321fc93e9f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack