# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.gate.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'gate', 'function_path': 'animated_java:gate/animations/openclosetoggle/resume'}
tag @s add aj.gate.animation.openclosetoggle.playing

execute as @n[scores={gate_right_click=1..}] run function inventory:hotbar/set {"text":"'Keycard was inserted into the slot."}