# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.door_card0.node.base] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_base set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.door_card0.node.wind0] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wind0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.door_card0.node.wind1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_wind1 set from storage aj:uuid main.out