# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.m4a1.node.m4a1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_m4a1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.m4a1.node.l_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_l_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.m4a1.node.r_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_r_arm set from storage aj:uuid main.out