# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '80511e6a5187226726ae8bf69f8c4745b891c764e468e9d9a2fdd0c9d49910c1'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack