# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f14e4447395ed1366c27be8877a837e31d8d111c632f25d42b8929745b5e0732'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack