# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '095d1deec817fb0de9bd17c99b01991f9998d7abeb7fb67ddba1bdb76e89cd73'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack