# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp939.root] run return 0
execute if entity @s[tag=aj.scp939.animation.idle.playing] run function animated_java:scp939/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp939.animation.attack.playing] run function animated_java:scp939/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.scp939.animation.walk.playing] run function animated_java:scp939/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.scp939.animation.run.playing] run function animated_java:scp939/animations/run/zzz/on_tick
execute on passengers run rotate @s ~ ~