# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.p.root] run return 0
execute on passengers if entity @s[tag=aj.p.data] unless data entity @s {data:{rigHash: '7d6f132076865eeb4e448c37a50de1a0df9a2421eb9a10251af3d4f527a382ca'}} on vehicle run function animated_java:p/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1