# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_lever) {transformation: [-1f,0f,0f,0f,0f,-1f,0.0056f,0.5f,0f,0.0056f,1f,-0.3594f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
tag @n[tag=lever] add proceed

#initialize event 1
execute as @n[tag=lever] if entity @s[tag=lczlockdown] run function events:1/init