# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp1048a/animations/pause_all
tag @s add aj.scp1048a.animation.shriek.playing
tag @n[type=husk, tag=scp1048Aorigin] add shriek
scoreboard players set @s aj.shriek.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp1048a/animations/shriek/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only

attribute @n[type=husk, tag=scp1048Aorigin] minecraft:movement_speed modifier add 1522-2-5-8-1 -1.0 add_value