# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'c2ebde81ec6301265b8d3b7d26a20b679c030a5d4af13930ac475634d62d006d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack