# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp008.root] run return 0
execute if entity @s[tag=aj.scp008.animation.close.playing] run function animated_java:scp008/animations/close/zzz/on_tick
execute on passengers run rotate @s ~ ~