# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:lever rig_hash set value '9d01aaabec093b797c6fe8afd02de3dc0d2f210c1358fc3b6fc6826049c6e5a7'
scoreboard objectives add aj.switch.frame dummy