# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ec549cbbaeaa000951c81d9713eab0b923965b49c763041d0746c21dc09149f8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack