# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '8eae22dd517ef1b985f193b422b61720e77a0d2a602e39af3ee44f444a90172c'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack