# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b8575c72001ac8f864ae312b8bb3647a80ffa9860ed3616391c83eee4c2f9fae'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack