# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a938a85b81e80d108726b6ca9179bbebe9e7cb2f127d38028028aa85762d089f'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack