# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '6af42e31c440b1e6a7bf4e49bd723798455eb651291f8a7f3088cff77d2aa625'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack