# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:door0 rig_hash set value '42186dac4257e5a9785ba0d97645d0a5870a4b5c4e02383d4f20c54f48b457f0'
scoreboard objectives add aj.openclosetoggle.frame dummy