# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp1048 rig_hash set value 'f14e4447395ed1366c27be8877a837e31d8d111c632f25d42b8929745b5e0732'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.greet.frame dummy