# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp1048 rig_hash set value '095d1deec817fb0de9bd17c99b01991f9998d7abeb7fb67ddba1bdb76e89cd73'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.greet.frame dummy