# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.914_button.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': '914_button', 'function_path': 'animated_java:914_button/animations/change_mode/next_frame'}
execute if score @s aj.change_mode.frame matches 11.. run scoreboard players set @s aj.change_mode.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.change_mode.frame
execute at @s run function animated_java:914_button/animations/change_mode/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.change_mode.frame 1