# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.914_button.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': '914_button', 'function_path': 'animated_java:914_button/animations/change_mode/play'}
tag @s add aj.914_button.animation.change_mode.playing
scoreboard players set @s aj.change_mode.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:914_button/animations/change_mode/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only