# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:914_button/animations/pause_all
tag @s add aj.914_button.animation.change_mode.playing
scoreboard players set @s aj.change_mode.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:914_button/animations/change_mode/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only