# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '35190fbffaf5750949837f470c71f0f3d20e3c86fc51990cb9bbf187a38c075d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack