# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp049.root] run return 0
execute on passengers if entity @s[tag=aj.scp049.data] unless data entity @s {data:{rigHash: '1067b1d03b03fc48362f065ebe73c94f7932794d33785889871e61379b8bb680'}} on vehicle run function animated_java:scp049/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1