# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp049.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.scp049.animation.idle.playing] run function animated_java:scp049/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp049.animation.contain.playing] run function animated_java:scp049/animations/contain/zzz/on_tick
execute if entity @s[tag=aj.scp049.animation.idle_contain.playing] run function animated_java:scp049/animations/idle_contain/zzz/on_tick
execute if entity @s[tag=aj.scp049.animation.revive.playing] run function animated_java:scp049/animations/revive/zzz/on_tick
execute if entity @s[tag=aj.scp049.animation.walk.playing] run function animated_java:scp049/animations/walk/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~