# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:914_start rig_hash set value '06a952b8b325aa3e70e4ad77ccd093d1ec7a8a2911f982854743c248d8baddf7'
scoreboard objectives add aj.start.frame dummy