# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '7981a80a01c31402e12f09f94ab2ba32e0b09df7015b8f1be9b39205283cd0eb'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack