# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'a95217320baa33077b9d709e27725c342223dced3834ad7cd818ecd5a6a9c2d0'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack