# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scp1048.animation.walk.playing
tag @s remove aj.scp1048.animation.idle.playing
tag @s remove aj.scp1048.animation.greet.playing