# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ff9241232fcf49a93adaada36776ba3aadb58a1d75bb2d6c9fcaad6dacc14025'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack