# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b40e3534e9b2574a3677181973bdc080f63490e1484affa0437c974f0276e876'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack