# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp049_2d/animations/walk/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.walk.frame 1