# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp650.root] run return 0
execute if entity @s[tag=aj.scp650.animation.switch.playing] run function animated_java:scp650/animations/switch/zzz/on_tick
execute on passengers run rotate @s ~ ~