# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.scp096.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'scp096', 'function_path': 'animated_java:scp096/animations/run/play'}
tag @s add aj.scp096.animation.run.playing
scoreboard players set @s aj.run.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp096/animations/run/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only