# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ci.root] run return 0
execute if entity @s[tag=aj.ci.animation.walk.playing] run function animated_java:ci/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~