# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~-1 ~ ~ minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~ ~1 ~ minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r0] at @s run setblock ~ ~ ~ minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~ ~-1 minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~1 ~ minecraft:lightning_rod
execute as @n[tag=door_marker,tag=r1] at @s run setblock ~ ~ ~ minecraft:lightning_rod
execute if entity @n[tag=door_marker,tag=r0] as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker,tag=r0] positioned ~0.5 ~ ~ as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker,tag=r0] positioned ~-0.5 ~ ~ as @a[distance=..0.5] run tp @s ~ ~ ~0.5
execute if entity @n[tag=door_marker,tag=r1] as @a[distance=..0.5] run tp @s ~0.5 ~ ~
execute if entity @n[tag=door_marker,tag=r1] positioned ~ ~ ~0.5 as @a[distance=..0.5] run tp @s ~0.5 ~ ~
execute if entity @n[tag=door_marker,tag=r1] positioned ~ ~ ~-0.5 as @a[distance=..0.5] run tp @s ~0.5 ~ ~