# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.door1.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'door1', 'function_path': 'animated_java:door1/remove/this'}
tag @n[tag=door_marker_hcz] add dr.not_rendered

execute at @n[tag=door_marker_hcz,tag=r0] run setblock ~-1 ~1 ~ minecraft:air
execute at @n[tag=door_marker_hcz,tag=r0] run setblock ~-1 ~ ~ minecraft:air
execute at @n[tag=door_marker_hcz,tag=r0] run setblock ~ ~1 ~ minecraft:air
execute at @n[tag=door_marker_hcz,tag=r0] run setblock ~ ~ ~ minecraft:air
execute at @n[tag=door_marker_hcz,tag=r1] run setblock ~ ~1 ~-1 minecraft:air
execute at @n[tag=door_marker_hcz,tag=r1] run setblock ~ ~ ~-1 minecraft:air
execute at @n[tag=door_marker_hcz,tag=r1] run setblock ~ ~1 ~ minecraft:air
execute at @n[tag=door_marker_hcz,tag=r1] run setblock ~ ~ ~ minecraft:air

execute on passengers run kill @s
kill @s