# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.infected008.root] run return 0
execute if entity @s[tag=aj.infected008.animation.idle.playing] run function animated_java:infected008/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.infected008.animation.walk.playing] run function animated_java:infected008/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.infected008.animation.attack.playing] run function animated_java:infected008/animations/attack/zzz/on_tick
execute if entity @s[tag=aj.infected008.animation.wake.playing] run function animated_java:infected008/animations/wake/zzz/on_tick
execute if entity @s[tag=aj.infected008.animation.death.playing] run function animated_java:infected008/animations/death/zzz/on_tick
execute on passengers run rotate @s ~ ~