# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '88b6d79bc9149fdba70d62aaa168211286392cf88251fa25149c557b1f604038'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack