# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp1048/animations/pause_all
tag @s add aj.scp1048.animation.greet.playing
scoreboard players set @s aj.greet.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp1048/animations/greet/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only

rotate @n[type=pig, tag=scp1048origin] facing entity @p eyes
attribute @n[type=pig, tag=scp1048origin] minecraft:movement_speed modifier add 1521-2-5-8-1 -1.0 add_value
playsound cb:scp1048.greet ambient @a ~ ~ ~ 1.5 1 1