# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp1048/animations/pause_all
scoreboard players set @s aj.greet.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp1048/animations/greet/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only

tag @p[tag=!dead,tag=greetTarget] remove greetTarget
scoreboard players operation @n[type=pig, tag=scp1048origin] greet = .max greet
attribute @n[type=pig, tag=scp1048origin] minecraft:movement_speed modifier remove 1521-2-5-8-1