# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:infected008/animations/attack/zzz/apply_frame {frame: 47}
scoreboard players add @s aj.attack.frame 1