# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_door) {transformation: [-2f,0f,0f,-1.1664f,0f,2f,0f,0f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute anchored eyes positioned ^ ^ ^ run setblock ~ ~ ~ air
execute anchored eyes positioned ^ ^1 ^ run setblock ~ ~ ~ air
execute anchored eyes positioned ^1 ^ ^ run setblock ~ ~ ~ air
execute anchored eyes positioned ^1 ^1 ^ run setblock ~ ~ ~ air