# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add aj.door0_sc.animation.openclosetoggle.playing

execute as @p[scores={door_right_click=1..}] run function inventory:hotbar/set {"text":"'The fingerprints appear to match."}