# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp096/animations/idle_sit_/zzz/apply_frame {frame: 75}
scoreboard players add @s aj.idle_sit_.frame 1