# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.scientist.animation.idle.playing
tag @s remove aj.scientist.animation.death.playing
tag @s remove aj.scientist.animation.corpse.playing