# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:singledoor1 rig_hash set value '99bafdb2771af10d41386a0936a867d9c9d8a970313dc7a0e4307ef25ef2cbf5'
scoreboard objectives add aj.open_close_toggle.frame dummy