# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2.3333f,0f,0f,1.5625f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2.3333f,0f,0f,-1.4375f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
playsound cb:gate.open ambient @a[distance=..32] ~ ~ ~ 1.5 1 1
tag @n[tag=gate_marker] add proceed