# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2.3333f,0f,0f,1.5625f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2.3333f,0f,0f,-1.4375f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
particle minecraft:dust_plume ~ ~0.75 ~ 0.1 1.5 0.1 0 200
tag @n[tag=gate_marker] add closed
tag @n[tag=gate_marker] remove opened
tag @n[tag=gate_marker] remove proceed