# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2.3333f,0f,0f,1.9297f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2.3333f,0f,0f,-1.8032f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=gate] if entity @s[tag=blocked] run playsound cb:scp079.door1 ambient @a[distance=..48] ~ ~1 ~ 0.5 1 1
execute as @n[tag=gate] if entity @s[tag=blocked] run function animated_java:gate/animations/openclosetoggle/set_frame {"frame":"111"}