# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2.3333f,0f,0f,4.5616f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2.3333f,0f,0f,-4.4241f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute as @n[tag=gate_marker] at @s run function animated_java:gate/animations/openclosetoggle/pause
tag @n[tag=gate_marker] remove proceed
tag @n[tag=gate_marker] remove closed
tag @n[tag=gate_marker] add opened