# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_wind0) {transformation: [-2.3333f,0f,0f,4.0165f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2.3333f,0f,0f,-3.8915f,0f,2.3333f,0f,1.5f,0f,0f,-2.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute at @n[tag=gate_marker,tag=r0] run fill ~ ~1 ~-3 ~ ~2 ~-3 lightning_rod[facing=south]
execute at @n[tag=gate_marker,tag=r0] run fill ~ ~1 ~2 ~ ~2 ~2 lightning_rod[facing=south]

execute at @n[tag=gate_marker,tag=r1] run fill ~-3 ~1 ~ ~-3 ~2 ~ lightning_rod[facing=east]
execute at @n[tag=gate_marker,tag=r1] run fill ~2 ~1 ~ ~2 ~2 ~ lightning_rod[facing=east]