# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp066/animations/wallow/zzz/apply_frame {frame: 29}
scoreboard players add @s aj.wallow.frame 1