# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_base) {transformation: [-2.9167f,0f,0f,-0.9375f,0f,2.9167f,0f,0f,0f,0f,-2.9167f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind0) {transformation: [-2f,0f,0f,0f,0f,2f,0f,0f,0f,0f,-2f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_wind1) {transformation: [-2f,0f,0f,0f,0f,2f,0f,0f,0f,0f,-2f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:door_card0/animations/openclosetoggle/zzz/frames/0_root_commands