# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.point.frame matches 60.. run scoreboard players set @s aj.point.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.point.frame
execute at @s run function animated_java:scp1499_1/animations/point/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.point.frame 1