# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp1499_1/animations/pause_all
tag @s add aj.scp1499_1.animation.point.playing
scoreboard players set @s aj.point.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:scp1499_1/animations/point/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only

attribute @n[tag=scp1499_1origin] movement_speed modifier add 1499-1-0-0-0 -1.0 add_value