# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp049_2.root] run return 0
execute on passengers if entity @s[tag=aj.scp049_2.data] unless data entity @s {data:{rigHash: 'c074ccad005740302619a13e3c3d2ceb289254af4cdcefdafb345dcad887a612'}} on vehicle run function animated_java:scp049_2/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1