# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.scp049_2.root] run return 0
execute if entity @s[tag=aj.scp049_2.animation.walk.playing] run function animated_java:scp049_2/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.scp049_2.animation.idle.playing] run function animated_java:scp049_2/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.scp049_2.animation.attack.playing] run function animated_java:scp049_2/animations/attack/zzz/on_tick
execute on passengers run rotate @s ~ ~