# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door0.root] run return 0
execute on passengers if entity @s[tag=aj.door0.data] unless data entity @s {data:{rigHash: '375826f280c90781f77a6ffd8f52f55631c89b158a8a42be6687865e89614af8'}} on vehicle run function animated_java:door0/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1