# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:914_button rig_hash set value 'c3938e4ddb8a18fcfa2bb7638d0c584bfa46dfd0d4ed3fa2b441a070fbdb77ad'
scoreboard objectives add aj.change_mode.frame dummy