# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-0.9971f,-0.0752f,-0.0068f,-0.0625f,-0.0103f,0.0455f,0.9989f,0.1969f,-0.0748f,0.9961f,-0.0462f,1.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=aj.infected008.root] at @s if entity @s[tag=d_tesla] run particle minecraft:smoke ~ ~0.45 ~ 0.4 0 0.4 0.001 15 force