# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-0.9957f,-0.067f,0.0633f,-0.0063f,-0.0432f,0.9461f,0.321f,0.8719f,-0.0814f,0.3169f,-0.945f,0.2537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9981f,0.029f,0.0544f,-0.05f,0.0284f,0.9995f,-0.0105f,1.625f,-0.0547f,-0.0089f,-0.9985f,0.5156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.921f,-0.3829f,0.0722f,0.2359f,-0.3383f,0.8777f,0.3394f,1.4875f,-0.1933f,0.2882f,-0.9379f,0.4687f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9401f,0.2854f,-0.1864f,-0.3203f,0.2378f,0.9409f,0.2413f,1.4766f,0.2443f,0.1825f,-0.9524f,0.4297f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.983f,-0.1652f,0.0806f,0.125f,-0.0545f,0.6807f,0.7305f,0.8938f,-0.1755f,0.7137f,-0.6781f,0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.9952f,0.0972f,0.0059f,-0.125f,0.0699f,0.6708f,0.7384f,0.8781f,0.0678f,0.7353f,-0.6744f,0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute as @n[tag=aj.infected008.root] at @s if entity @s[tag=d_tesla] run particle minecraft:smoke ~ ~0.45 ~ 0.4 0 0.4 0.005 30 force