# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:singledoor0 rig_hash set value 'f2c14c95fbc58b695a625265464384d38406de9e186ba03759cab3adad8ed6b8'
scoreboard objectives add aj.openclosetoggle.frame dummy