# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b1ab7207065af6d91bf7f5835edd8d3b123eec0d96d763d614e6992146a06033'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack