# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'f2c14c95fbc58b695a625265464384d38406de9e186ba03759cab3adad8ed6b8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack