# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:scp096/animations/run/zzz/apply_frame {frame: 16}
scoreboard players add @s aj.run.frame 1