# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.greet.frame matches 43.. run scoreboard players set @s aj.greet.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.greet.frame
execute at @s run function animated_java:scp1048a/animations/greet/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.greet.frame 1