# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:door0_sc rig_hash set value 'e1a5fffdb294055682148cb5dc8dca55a3f49863917db8b23ce9d0321fc93e9f'
scoreboard objectives add aj.openclosetoggle.frame dummy