# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door914.root] run return 0
execute on passengers if entity @s[tag=aj.door914.data] unless data entity @s {data:{rigHash: '9a6c6f07b13465674f5271c6cf51a4cddcbed20abd4d0a67c4b85098f2be6e45'}} on vehicle run function animated_java:door914/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1