# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.door914.root] run return 0
execute if entity @s[tag=aj.door914.animation.open.playing] run function animated_java:door914/animations/open/zzz/on_tick
execute if entity @s[tag=aj.door914.animation.close.playing] run function animated_java:door914/animations/close/zzz/on_tick
execute on passengers run rotate @s ~ ~