# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'b544adb38d285199ab6c5749f085b33795fb0204dc411182b8a091384ef30ef8'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack