# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.rage_in_.frame
function animated_java:scp096/animations/rage_in_/zzz/apply_frame with storage aj:temp args
execute if score @s aj.rage_in_.frame matches 115 run return run function animated_java:scp096/animations/rage_in_/stop
scoreboard players add @s aj.rage_in_.frame 1