# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door.open ambient @a[distance=..24] ~ ~ ~ 1 1 1

#g 008 special
execute as @n[tag=aj.singledoor0.root] if entity @s[tag=008_0] as @n[tag=008_1] run function animated_java:singledoor0/animations/openclosetoggle/resume

tag @n[tag=aj.singledoor0.root] add opened
tag @n[tag=aj.singledoor0.root] remove closed

scoreboard players operation @n[tag=aj.singledoor0.root] door_interact_cd = max door_interact_cd

execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~-1 ~ ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=west]

execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~ ~-1 minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=south]