# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound cb:door.close ambient @a[distance=..24] ~ ~ ~ 1 1 1

#g 008 special
execute as @n[tag=aj.singledoor0.root] if entity @s[tag=008_0] as @n[tag=008_1] run function animated_java:singledoor0/animations/openclosetoggle/resume

tag @n[tag=aj.singledoor0.root] add closed
tag @n[tag=aj.singledoor0.root] remove opened

scoreboard players operation @n[tag=aj.singledoor0.root] door_interact_cd = max door_interact_cd