# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~-1 ~1 ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~-1 ~ ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=west]
execute as @n[tag=aj.singledoor0.root, tag=r0] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=west]

execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~1 ~-1 minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~ ~-1 minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~1 ~ minecraft:lightning_rod[facing=south]
execute as @n[tag=aj.singledoor0.root, tag=r1] at @s run setblock ~ ~ ~ minecraft:lightning_rod[facing=south]