# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '9490342ed5eb9a96f127256707182f21b106679a054bda536c433785982bb2ef'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack