# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:scp049_2d rig_hash set value '80511e6a5187226726ae8bf69f8c4745b891c764e468e9d9a2fdd0c9d49910c1'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.attack.frame dummy