# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:door1 rig_hash set value '9490342ed5eb9a96f127256707182f21b106679a054bda536c433785982bb2ef'
scoreboard objectives add aj.open_close_toggle.frame dummy