# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_s) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5625f,0f,0f,-1f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_p) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5156f,0f,0f,-1f,-0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-1.0417f,0f,0f,-0.5625f,0f,1.0417f,0f,0.5f,0f,0f,-1.0417f,-1.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-1.0417f,0f,0f,0.5625f,0f,1.0397f,-0.0634f,0.5f,0f,-0.0634f,-1.0397f,-1.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}