# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-0.9991f,-0.0094f,-0.0419f,0f,-0.0137f,0.9946f,0.1026f,0.825f,0.0408f,0.1031f,-0.9938f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9714f,-0.0658f,-0.2282f,0f,-0.118f,0.9676f,0.2232f,1.65f,0.2061f,0.2438f,-0.9477f,0.0629f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9252f,-0.3041f,-0.2272f,0.2708f,-0.2893f,0.9524f,-0.0967f,1.5125f,0.2458f,-0.0238f,-0.969f,0.0127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [0.9618f,-0.2312f,0.1463f,-0.4687f,-0.0831f,0.2628f,0.9613f,1.5125f,-0.2607f,-0.9367f,0.2336f,0.1812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

execute store result storage cb:scp1499_1damage min int 1 run scoreboard players get damageMin 1499_1
execute store result storage cb:scp1499_1damage max int 1 run scoreboard players get damageMax 1499_1
execute store result storage cb:scp1499_1bleeding min int 1 run scoreboard players get bleedingMin 1499_1
execute store result storage cb:scp1499_1bleeding max int 1 run scoreboard players get bleedingMax 1499_1

function scp1499_1:define_damage with storage cb:scp1499_1damage
function scp1499_1:define_bleeding with storage cb:scp1499_1bleeding

execute anchored eyes positioned ^ ^ ^1 as @p[distance=..1.6] if predicate scp1499_1:60 run function scp1499_1:apply_bleeding
execute anchored eyes positioned ^ ^ ^1 as @p[distance=..1.6] run scoreboard players operation @s health -= damage 1499_1

execute anchored eyes positioned ^ ^ ^1 as @p[distance=..1.6] run playsound cb:d9341.damage10 ambient @s ~ ~ ~ 1 1 1
execute anchored eyes positioned ^ ^ ^1 as @p[distance=..1.6] run playsound cb:d9341.damage10 ambient @a[distance=0.01..] ~ ~1 ~ 1.25 1 1

execute anchored eyes positioned ^ ^ ^1 as @p[distance=..1.6] if score @s health <= 0 math run tag @s add d_1499_1