# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-0.9998f,0f,-0.0175f,0f,0f,1f,0f,0.8125f,0.0175f,0f,-0.9998f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9992f,-0.0349f,0.0168f,0f,-0.0346f,0.9992f,0.018f,1.6446f,-0.0174f,0.0175f,-0.9997f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.7871f,0.5998f,0.1443f,0.2313f,-0.103f,0.1029f,-0.9893f,1.5045f,-0.6082f,-0.7935f,-0.0192f,0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_gun) {transformation: [-0.9474f,0.0915f,-0.3068f,-0.1755f,0.0573f,0.9913f,0.1187f,1.4878f,0.315f,0.0949f,-0.9443f,0.6239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.9474f,-0.3068f,-0.0915f,-0.2812f,0.0573f,0.1187f,-0.9913f,1.5045f,0.315f,-0.9443f,-0.0949f,0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-0.9964f,-0.0346f,-0.0779f,0.1375f,-0.0458f,0.988f,0.1474f,0.8229f,0.0719f,0.1504f,-0.986f,-0.0229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_leg) {transformation: [-0.998f,0.0403f,0.0482f,-0.1375f,0.0367f,0.9965f,-0.075f,0.7875f,-0.0511f,-0.0731f,-0.996f,0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

function scps:sounds/step/heavy {"pitch":"0.9"}