# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0.0078f,0f,0f,1f,0f,0.8125f,-0.0078f,0f,-1f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.9992f,-0.0349f,0.0168f,0f,-0.0346f,0.9992f,0.018f,1.6451f,-0.0174f,0.0175f,-0.9997f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_arm) {transformation: [-0.7871f,0.6001f,0.1428f,0.2313f,-0.103f,0.1004f,-0.9896f,1.5116f,-0.6082f,-0.7936f,-0.0172f,0.0563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_gun) {transformation: [-0.9474f,0.0908f,-0.307f,-0.1754f,0.0573f,0.9916f,0.1163f,1.4884f,0.315f,0.0926f,-0.9446f,0.6239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_r_arm) {transformation: [-0.9474f,-0.307f,-0.0908f,-0.2812f,0.0573f,0.1163f,-0.9916f,1.5036f,0.315f,-0.9446f,-0.0926f,0.025f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_l_leg) {transformation: [-0.9886f,-0.0728f,-0.1317f,0.1375f,-0.065f,0.9959f,-0.0631f,0.7875f,0.1358f,-0.0538f,-0.9893f,0.0938f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}

function scps:sounds/step/heavy {"pitch":"0.9"}